// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: protos/email/email.proto

package email

import (
	context "context"
	grpc "google.golang.org/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_protos_email_email_proto protoreflect.FileDescriptor

var file_protos_email_email_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2f, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x07, 0x0a, 0x05, 0x45, 0x4d,
	0x61, 0x69, 0x6c, 0x42, 0x08, 0x5a, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_protos_email_email_proto_goTypes = []interface{}{}
var file_protos_email_email_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_email_email_proto_init() }
func file_protos_email_email_proto_init() {
	if File_protos_email_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_email_email_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_email_email_proto_goTypes,
		DependencyIndexes: file_protos_email_email_proto_depIdxs,
	}.Build()
	File_protos_email_email_proto = out.File
	file_protos_email_email_proto_rawDesc = nil
	file_protos_email_email_proto_goTypes = nil
	file_protos_email_email_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EMailClient is the client API for EMail service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EMailClient interface {
}

type eMailClient struct {
	cc grpc.ClientConnInterface
}

func NewEMailClient(cc grpc.ClientConnInterface) EMailClient {
	return &eMailClient{cc}
}

// EMailServer is the server API for EMail service.
type EMailServer interface {
}

// UnimplementedEMailServer can be embedded to have forward compatible implementations.
type UnimplementedEMailServer struct {
}

func RegisterEMailServer(s *grpc.Server, srv EMailServer) {
	s.RegisterService(&_EMail_serviceDesc, srv)
}

var _EMail_serviceDesc = grpc.ServiceDesc{
	ServiceName: "EMail",
	HandlerType: (*EMailServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "protos/email/email.proto",
}
